[2024-12-08T13:10:34.950+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.create_table manual__2024-12-08T13:10:24.570986+00:00 [queued]>
[2024-12-08T13:10:34.964+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.create_table manual__2024-12-08T13:10:24.570986+00:00 [queued]>
[2024-12-08T13:10:34.965+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-12-08T13:10:34.977+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): create_table> on 2024-12-08 13:10:24.570986+00:00
[2024-12-08T13:10:34.986+0000] {standard_task_runner.py:60} INFO - Started process 1037 to run task
[2024-12-08T13:10:34.991+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'create_table', 'manual__2024-12-08T13:10:24.570986+00:00', '--job-id', '457', '--raw', '--subdir', 'DAGS_FOLDER/extract.py', '--cfg-path', '/tmp/tmpswuq5oh0']
[2024-12-08T13:10:34.992+0000] {standard_task_runner.py:88} INFO - Job 457: Subtask create_table
[2024-12-08T13:10:35.009+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-08T13:10:35.044+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dag.create_table manual__2024-12-08T13:10:24.570986+00:00 [running]> on host 08c9c3bec828
[2024-12-08T13:10:35.147+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thiernosidybah232@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-12-08T13:10:24.570986+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-08T13:10:24.570986+00:00'
[2024-12-08T13:10:35.148+0000] {sql.py:276} INFO - Executing: 
                        CREATE TABLE IF NOT EXISTS Weather_table(
                            city TEXT,
                            weather_description TEXT , 
                            temp_c NUMERIC,
                            feels_like_celsius NUMERIC, 
                            min_temp_c NUMERIC,
                            max_temp_c NUMERIC, 
                            pressure NUMERIC, 
                            humidity NUMERIC, 
                            wind_speed NUMERIC, 
                            time_of_record TIMESTAMP, 
                            sunrise_time TIMESTAMP, 
                            sunset_time TIMESTAMP ); 
                    
[2024-12-08T13:10:35.165+0000] {base.py:83} INFO - Using connection ID 'weather_database_connection' for task execution.
[2024-12-08T13:10:35.175+0000] {base.py:83} INFO - Using connection ID 'weather_database_connection' for task execution.
[2024-12-08T13:10:35.182+0000] {sql.py:450} INFO - Running statement: 
                        CREATE TABLE IF NOT EXISTS Weather_table(
                            city TEXT,
                            weather_description TEXT , 
                            temp_c NUMERIC,
                            feels_like_celsius NUMERIC, 
                            min_temp_c NUMERIC,
                            max_temp_c NUMERIC, 
                            pressure NUMERIC, 
                            humidity NUMERIC, 
                            wind_speed NUMERIC, 
                            time_of_record TIMESTAMP, 
                            sunrise_time TIMESTAMP, 
                            sunset_time TIMESTAMP ); 
                    , parameters: None
[2024-12-08T13:10:35.198+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=create_table, execution_date=20241208T131024, start_date=20241208T131034, end_date=20241208T131035
[2024-12-08T13:10:35.243+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-12-08T13:10:35.294+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
