[2024-12-07T19:20:21.961+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.insert_book_data manual__2024-12-07T19:20:14.893087+00:00 [queued]>
[2024-12-07T19:20:21.974+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.insert_book_data manual__2024-12-07T19:20:14.893087+00:00 [queued]>
[2024-12-07T19:20:21.975+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-12-07T19:20:21.986+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): insert_book_data> on 2024-12-07 19:20:14.893087+00:00
[2024-12-07T19:20:21.990+0000] {standard_task_runner.py:60} INFO - Started process 12323 to run task
[2024-12-07T19:20:21.993+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'insert_book_data', 'manual__2024-12-07T19:20:14.893087+00:00', '--job-id', '295', '--raw', '--subdir', 'DAGS_FOLDER/extract.py', '--cfg-path', '/tmp/tmpysydo1sz']
[2024-12-07T19:20:21.994+0000] {standard_task_runner.py:88} INFO - Job 295: Subtask insert_book_data
[2024-12-07T19:20:22.005+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-07T19:20:22.053+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dag.insert_book_data manual__2024-12-07T19:20:14.893087+00:00 [running]> on host 8271fbcad3f4
[2024-12-07T19:20:22.165+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thiernosidybah232@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='insert_book_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-07T19:20:14.893087+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-07T19:20:14.893087+00:00'
[2024-12-07T19:20:22.220+0000] {logging_mixin.py:188} INFO -                        City  ...   Sunset_Local_time
0  Arrondissement de Nantes  ... 2024-12-07 17:16:58

[1 rows x 10 columns]
[2024-12-07T19:20:22.226+0000] {base.py:83} INFO - Using connection ID 'weather_database_connection' for task execution.
[2024-12-07T19:20:22.235+0000] {logging_mixin.py:188} INFO -                        City  ...   Sunset_Local_time
0  Arrondissement de Nantes  ... 2024-12-07 17:16:58

[1 rows x 10 columns]
[2024-12-07T19:20:22.238+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-12-07T19:20:22.246+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=insert_book_data, execution_date=20241207T192014, start_date=20241207T192021, end_date=20241207T192022
[2024-12-07T19:20:22.285+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-12-07T19:20:22.307+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
